### ISSUE TITLE
how to using this tools to publish text to rviz2

### ISSUE THREAD

**Issue by mryao57** [teamspatzenhirn/overlay_rviz_plugins#14]
Hello, can you tell me the usage or some documents about how to using this tools on rviz2? 
thinks a lot!

**Comment by ottojo** [comment]
Hi! All currently available documentation is found here: https://docs.ros.org/en/rolling/p/rviz_2d_overlay_plugins/generated/doxygen/html/

TLDR: Install the plugin (`sudo apt install ros-humble-rviz-2d-overlay-plugins`), publish a message (this for text overlay: https://github.com/teamspatzenhirn/rviz_2d_overlay_plugins/blob/main/rviz_2d_overlay_msgs/msg/OverlayText.msg, this for gauge overlay: https://github.com/ros2/common_interfaces/blob/rolling/std_msgs/msg/Float32.msg), then select the topics in rviz

**Comment by mryao57** [comment]
已收到您的邮件。祝您生活愉快，工作顺利！
                                                     ---姚广华

**Comment by rem821** [comment]
@ottojo Hi!
I'm migrating a project from ROS1 to ROS2 and I'd like to continue using OverlayText previously from jsk. 
However, I'm running into difficulties while trying to link your code in CMake.

I've added the dependency in `package.xml`
`<depend>rviz_2d_overlay_msgs</depend>`

in `CMakeLists.txt` I've also included the package:

`find_package(visualization_msgs REQUIRED)`
`ament_target_dependencies(${PROJECT_NAME} ... rviz_2d_overlay_msgs)`

but when I try to create the publisher
`node_->create_publisher<rviz_2d_overlay_msgs::msg::OverlayText>(topic, 0)`

I get the following linking error:
```/opt/ros/humble/include/rclcpp/rclcpp/get_message_type_support_handle.hpp:50: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<rviz_2d_overlay_msgs::msg::OverlayText_<std::allocator<void> > >()'```

Do you know what I'm missing by any chance?

**Comment by ottojo** [comment]
@rem821 I don't immediately see a problem, you are using the package as intended, and as far as i can see how we use it internally.
I see that we internally also have `rclcpp spatz_interfaces sensor_msgs` (`spatz_interfaces` comes from [this repo](https://github.com/teamspatzenhirn/spatz_interfaces/blob/master/CMakeLists.txt)) in our `ament_target_dependencies`, perhaps that pulls in some transitive dependency which we forgot to add in this package.

I seem to be able to build and link a test like this:
```c++
#include <rclcpp/rclcpp.hpp>
#include <rviz_2d_overlay_msgs/msg/overlay_text.hpp>

class TestNode : public rclcpp::Node {
  public:
    TestNode() :
        rclcpp::Node("test"),
        rcModeTextPub(create_publisher<rviz_2d_overlay_msgs::msg::OverlayText>("/overlay", rclcpp::QoS(1))) {
    }

  private:
    rclcpp::Publisher<rviz_2d_overlay_msgs::msg::OverlayText>::SharedPtr rcModeTextPub;
};

int main(int argc, char *argv[]) {
    rclcpp::init(argc, argv);
    rclcpp::spin(std::make_shared<TestNode>());
    rclcpp::shutdown();
    return 0;
}
```
```cmake
add_executable(testnode tn.cpp)
ament_target_dependencies(testnode rclcpp rviz_2d_overlay_msgs)
```

**Comment by rem821** [comment]
@ottojo Thanks for the quick reply! 
I can confirm the package links correctly now, the issue was that I've been incorrectly linking it to the parts of the code that had been compiled as a static library in CMake. 

Btw, kudos for porting this package to ROS2!

**Comment by ottojo** [comment]
I think this can be closed, especially now that it's possible to use a standard String message for text display, as documented here: https://github.com/teamspatzenhirn/rviz_2d_overlay_plugins/tree/main/rviz_2d_overlay_plugins#using-a-string-topic . Feel free to open a new issue if use is still unclear or problems persist.

**Comment by mryao57** [comment]
已收到您的邮件。祝您生活愉快，工作顺利！
                                                     ---姚广华
