### ISSUE TITLE
std_msgs/msg/String type as OverlayText

### ISSUE THREAD

**Issue by szepilot** [teamspatzenhirn/overlay_rviz_plugins#17]
hi,
thanks for the awesome work

can i maybe use `std_msgs/msg/String` instead of `rviz_2d_overlay_msgs/msg/OverlayText`?

or can i maybe relay it somehow? 

thanks

**Comment by ottojo** [comment]
Hi! This is currently not supported (and i dont think it is in the ROS1 version from JSK), but i think this could work just like the gauge display which only requires a `Float32` message.
I'm not sure how we would handle *both* `String` and `OverlayText` though, ideas and PRs are welcome!

It is of course also possible to write a small converter node, which subscribes to a `String`, publishes a `OverlayText` and perhaps exposes the other parameters as ROS parameters...
If you end up writing such a node, i'm sure it would be useful enough to add it to this repo, if you want.

**Comment by ottojo** [comment]
fixed by #18
